### ISSUE TITLE
Debugging a Firework that defuses children

### ISSUE THREAD

**Issue by bocklund** [hackingmaterials/atomate#170]
From @computron in [this Google Groups discussion](https://groups.google.com/d/msgid/atomate/bdaffbce-9f3f-4a2f-b2e9-c5dbda2c4d0c%40googlegroups.com?utm_medium=email&utm_source=footer):

> I am not sure what happened to the message, but Brandon replied:
>
> ========
> I saw that as well. Seems like the only place that could come from.
> 
> is it the correct behavior for jobs to be marked as COMPLETED rather than FIZZLED if this is the case? Is the rationale that I try parsing those outputs by hand?
>
> ========
>
>
>It is up to use to define what is the correct behavior. The "defuse" action happens when the VASP run completes OK, but something is still wrong. For example, let's say you hit the maximum number of ionic steps and didn't actually converge to your desired tolerance. The job didn't "fail" and the VASP outputs would look normal at first glance, but we also didn't succeed in getting what we want to proceed to the next step.

> Two options are:
> 1. Call that particular run COMPLETED but defuse remaining runs. This (the current behavior) reflects the idea that the run did in fact complete without any errors, but that we wouldn't want to continue on with the workflow.
> 2. Call that particular run FIZZLED; this would alert a user that this perhaps a run that needs some kind of "fixing".

> I'm happy to discuss with some of the others if you think (2) is the better way forward. Let me know.

Thanks. This actually cleared it up for me. I think option (1) you presented makes more sense than (2) because in this instance the code behaved correctly and based on some configuration determined not to continue.

What could be improved is 

1. The behavior of the parsing the outputs. I was not aware that assimilating the result with a drone has some baked in behavior to defuse child Fireworks based on the results of the calculation.

Some things to consider
* Documentation that explains this behavior 
* Allow users to turn off the behavior of defuse on failed analysis 
* Allow users to set the parameters for defusing in their FWorker (we should definitely do this)

2. Defining the state. I haven't checked if there is any unsuccessful state output in the database. I guess if a Firework is COMPLETED, I should have suspected that there would be an entry in the tasks database. 

I think there should be some information in the defused Firework and the defusing Firework on why this happened. Especially if we can make that clear on the WebGUI because that's where users will look. Presumably the machinery to do this is already in FireWorks, we should just make better use of it here.

**Comment by computron** [comment]
Hi @bocklund 

Some comments on your suggestions

* I am supportive of more docs, but I would suggest you just add them wherever you would have wanted to see them
* There is an option in VaspToDb to turn this off already. But, that option is not reflected upstream (Firework or Workflow level). You could "promote" this option to the upstream objects, or you could add a powerup to modify this parameter, or you could set the default value of this parameter via ``config.py`` instead of having it default to True for all users, or you can have a FWorker option to set this parameter using ``env_chk`` like you suggested.
* Yes, I think this would be simple, feel free to implement if desired

2. Search for ``{"state": {"$ne": "successful"}}``. If any tasks exists, the errors should be listed in ``analysis.errors``.

**Comment by computron** [comment]
@bocklund I wanted to follow up on this issue

I can see why defusing the children when the parent calculation has a problem is a bit confusing. I pushed a commit (ba8bdb21f8c221c663bded46710a73ccc71c7f84) that adds an option in the ``config.py`` that lets you control the default behavior of this setting. Furthermore, the default is changed so that the parent job (the one with the problem) is marked as FIZZLED rather than defusing the children.

see config.py:

```
DEFUSE_UNSUCCESSFUL = "fizzle"  # this is a three-way toggle on what to do if your job looks OK, but is actually unconverged (either electronic or ionic). True -> mark job as COMPLETED, but defuse children. False --> do nothing, continue with workflow as normal. "fizzle" --> throw an error (mark this job as FIZZLED)
```

The error that's thrown by default should explain what failed.

I am going to close this for now, but let me know if you want to reopen (or submit another issue).
