### ISSUE TITLE
LcalcpolFW not working in offline mode

### ISSUE THREAD

**Issue by henriquemiranda** [hackingmaterials/atomate#217]
The problem seems to be that the Firework is creating a new folder and moving there:
t.append(CreateFolder(folder_name="polarization",change_dir=True))
The FW_offline.json is created one level up from the polarization folder.
When the function update_checkpoint in fireworks/core/rocket.py is called, the file is not found.

**Comment by henriquemiranda** [comment]
A quick and very dirty fix for this is to replace:
```
            offline_info = loadfn("FW_offline.json")
```
by:
```
            try:
                offline_info = loadfn("FW_offline.json")
            except:
                offline_info = loadfn("../FW_offline.json")
```
inside update_checkpoint in fireworks/core/rocket.py
A better and permanent solution should be to submit the polarization calculation as a separate firework.

**Comment by computron** [comment]
Thanks for finding this!

It seems that FireWorks itself does not support FireTasks changing directories.  However, I think FireWorks should support this use case. I've just pushed a commit to FWS (https://github.com/materialsproject/fireworks/commit/738d4aaaca58047fe3f3e0fdee299a6794bd0a79) so that the location of FW_offline.json is loaded from the initial launch directory rather than where the user changed dirs to.

As for the specific whether LCalcPolFW should separate the polarization calc into a separate FW, I think that is a separate issue. There are cases for and against that. The original author @blondegeek made the decision that keeping it in the same FW was best. Of course, if you have strong reasons to refactor and think you'd be able to perform the refactor, we'd certainly e open to that.

**Comment by computron** [comment]
Closing this issue -

This opens up a related issue in FWS if someone attempts task-level recovery, see https://github.com/materialsproject/fireworks/issues/269 if interested.
