### ISSUE TITLE
When MaxForceError occurred, why make EDIFFG/2 

### ISSUE THREAD

**Issue by xjf729** [hackingmaterials/atomate#219]
- When MaxForceError occurred, why custodian makes EDIFFG=EDIFFG/2 other than EDIFFG=EDIFFG*2 ?
- For a batch of calculations, especially when we are screening materials, we want to keep the same accuracy. So I think parameters like EDIFF/EDIFFG should be not be changed for some individual calculations. Is that right? How can I turn off custodian in atomate and keep the same EDIFFG parameter for a set of calculations? can I turn on/off custodian by _my_fworker.yaml_ conveniently?
- Although there is a MaxForceError, vasp also give a complete OUTCAR, which means that the calculation are done correctly? So why do custodian report an error?

**Comment by computron** [comment]
Hi,

Please post to the Google Group for all future questions
https://groups.google.com/forum/#!forum/atomate

1. When the max force error is encountered you want to make the convergence more strict. That is why you divide by two. A more strict convergence will give the potential of removing the residual forces since you will continue to relax the structure to an even tighter tolerance.

2. You can call the ``remove_custodian`` powerup on your workflow to just call VASP directly. See atomate.vasp.powerups.remove_custodian. So after creating your workflow (but before adding it to the FireWorks database), use something like: ``my_wf = remove_custodian(my_wf)``. This will turn off custodian for all workers which is probably what you want. If you want to control what workers use custodian, you will need to add some custom code that uses the FW env feature in the RunVaspCustodian Firework. Note that the RunVaspCustodian Firework also allows you to pick which handlers you want to use so that you can try to avoid the fixes that change any parameters.

3. Just because a calculation finishes doesn't mean that it is done correctly. For example you will get a valid OUTCAR even if you do not reach the electronic convergence or ionic convergence that you specified. Validation like max_force makes sure that your calculation is not only complete but correct. Feel free to turn off these features if you don't want them.
