### ISSUE TITLE
TasksMaterialsBuilder make _create_new_material copied props configurable?

### ISSUE THREAD

**Issue by janosh** [hackingmaterials/atomate#676]
`TasksMaterialsBuilder._create_new_material()` hard-codes the root-level properties it copies from task docs to materials docs.

https://github.com/hackingmaterials/atomate/blob/c3db7f8ccef215a64b946aee956d12d0b051c888/atomate/vasp/builders/tasks_materials.py#L246-L256

I have a a use case that requires extending the list of copied properties. Would you be open to a PR that makes this list configurable?

**Comment by mkhorton** [comment]
I can't comment for the atomate maintainers and the builders within atomate, but most of the MP builder development is happening outside of atomate currently (in the `emmet` repo).

Depending on your needs, these builders may or may not be more appropriate for your project -- the system has some more complexity, but they're also more battle tested. As a design decision, these builders are also written in a workflow-agnostic way and do not incorporate workflow metadata (this is a trade-off and has both good and bad consequences). Running these builders separately also makes them more configurable for this kind of change, since you can make the change locally and run them as-needed.

The atomate builders, as I understand, are more to give people a starting point that's appropriate for most use cases.
