### ISSUE TITLE
Atomate.vasp.workflows not working 

### ISSUE THREAD

**Issue by J-Messmer** [hackingmaterials/atomate#692]
I am trying to run a workflow and keep getting this error. How do I fix this?

![image](https://user-images.githubusercontent.com/86315007/122963464-83a79680-d343-11eb-8483-33fbe6245dd2.png)

Please submit help issues to:
https://matsci.org/atomate

The Github issues is no longer used except for internal development purposes.

If you are unable to use the Discourse forum, you may submit an issue here, but you must **clearly** state the reason you are unable to use the Discourse forum in your ticket. Otherwise, your issue will be **closed** without response.

**Comment by itsshawnzhang** [comment]
Hello @J-Messmer

For all the general discussion of workflow errors, please use matsci discussion forum. 

Please submit help issues to:
https://matsci.org/atomate

The Github issues is no longer used except for internal development purposes.

If you are unable to use the Discourse forum, you may submit an issue here, but you must clearly state the reason you are unable to use the Discourse forum in your ticket. Otherwise, your issue will be closed without response.

I will close this issue now. Please let us know if you have any further problems or concerns. Cheers! : )
