### ISSUE TITLE
Regarding the connection of atomate input file with mongodb

### ISSUE THREAD

**Issue by dips96** [hackingmaterials/atomate#722]
Dear Sir,
We are facing a problem regarding the connecting mongodb with an atomate input file. We are able to connect our high performance cluster with mongodb database. However, after submitting it in queue, it is showing some error. I am attaching the code we have used here.
"# Create a bandstructure from the workflow from the atomate presets
def get_database():
    from pymongo import MongoClient
    import pymongo

    # Provide the mongodb atlas url to connect python to mongodb using pymongo
    CONNECTION_STRING = "mongodb+srv://diptendu:diptendu1996@cluster0.wr928.mongodb.net/test"

    # Create a connection using MongoClient. You can import MongoClient or use pymongo.MongoClient
    from pymongo import MongoClient
    client = MongoClient(CONNECTION_STRING)

    # Create the database for our example (we will use the same database throughout the tutorial
    return client['user_shopping_list']

# This is added so that many files can reuse the function get_database()
if __name__ == "__main__":

    # Get the database
    dbname = get_database()
import numpy as np
from pymatgen.core import Structure
from fireworks import LaunchPad
from atomate.vasp.workflows.presets.core import wf_bandstructure
from atomate.vasp.powerups import add_modify_incar

# load structure from file
struct = Structure.from_file('POSCAR')  # note: many file formats supported, see function docs

# create the Workflow
wf = wf_bandstructure(struct)".

Please help me regarding this. I will be very much grateful to you.

**Comment by itsshawnzhang** [comment]
Hello @dips96

For all the general discussion of workflow errors, please use [matsci](https://matsci.org/atomate) discussion forum.


Please submit help issues to:
https://matsci.org/atomate

The Github issues is no longer used except for internal development purposes.

If you are unable to use the Discourse forum, you may submit an issue here, but you must clearly state the reason you are unable to use the Discourse forum in your ticket. Otherwise, your issue will be closed without response.

I will close this issue now. Please let us know if you have any further problems or concerns. Cheers! : )
